### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by appkr** [jo-minjun/order-delivery-project#6]
오늘 발표 잘 끝내고, 이후에 시간날 때 아래 내용 검토하고 반영 바랍니다

- [ ] 불필요 코드 제거
- [x] Test의 중복 코드 Fixture 클래스로 추출
- [x] `OrderDto.productName: String` 필드 추가
- [ ] Gradle Multi Project 적용하고, order, delivery, payment, product 완전 분리
  - [ ] Event -> Message
  - [ ] SimulateApiCall***Adapter -> Rest***Adapter
  - [ ] Mocking을 사용하여 Test 코드 재작성

NOTE. 추후에 order 프로젝트에 Reactive Web, R2DBC를 적용해 볼겁니다
